### PR TITLE
feat: run each sample scene directly

### PR DESCRIPTION
**Pull request by homuler**
Currently, each sample scene cannot be run directly and `Start Scene` must be played first.

This PR enables us to run each scene directly.

### Major Changes
- Attach `Bootstrap` to each Solution object (disabled by default)
- Remove the Hello World example

### CODE REVIEW

**Comment by mgarbade** [comment]
This works in Unity Editor mode, but when I build only the "pose tracking" solution for android, I get the following logcat error:

```
com.DefaultCompany.MediaPipeUnityPlugin E/Unity: : LocalResourceManager is only supported on UnityEditor
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:LogError(String, Object)
    Mediapipe.Unity.MemoizedLogger:LogError(String, Object)
    Mediapipe.Unity.Logger:LogError(String, Object)
    Mediapipe.Unity.Logger:LogError(Object)
    Mediapipe.Unity.<Init>d__16:MoveNext()
    UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
    UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
    Mediapipe.Unity.Bootstrap:OnEnable()
    Mediapipe.Unity.Solution:FindBootstrap()
    Mediapipe.Unity.<Start>d__4:MoveNext()
    UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

I event tried selecting the two other AssetLoaderType options in the bootstrap component (Streaming Asset and Asset Bundle) but it still gave me an error.

(Sorry if this is the wrong place to post this comment)

**Comment by mgarbade** [comment]
Apparantly it does help to set the default AssetLoaderType to "Streaming Asset" in the clean version of the MediaPipeUnityPlugin.

Only when I'm importing the plugin into my own project and try to reproduce the same steps there I'm getting:

```
2022.04.25 16:38:01.607 15441 15524 Error Unity InternalException: Failed to load pose_detection.bytes: HTTP/1.1 404 Not Found
2022.04.25 16:38:01.607 15441 15524 Error Unity   at Mediapipe.Unity.StreamingAssetsResourceManager+<CreateCacheFile>d__14.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
2022.04.25 16:38:01.607 15441 15524 Error Unity   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
2022.04.25 16:38:01.607 15441 15524 Error Unity 
2022.04.25 16:38:01.609 15441 15524 Error Unity InternalException: Failed to load pose_landmark_full.bytes: HTTP/1.1 404 Not Found
2022.04.25 16:38:01.609 15441 15524 Error Unity   at Mediapipe.Unity.StreamingAssetsResourceManager+<CreateCacheFile>d__14.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
2022.04.25 16:38:01.609 15441 15524 Error Unity   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
2022.04.25 16:38:01.609 15441 15524 Error Unity 

```

**Comment by mgarbade** [comment]
As I said in the Unity Editor mode everything works fine. Even specifying "Streaming Asset" there. Though it gives a message:

```
StreamingAssetsResourceManager: pose_detection.bytes will not be copied to C:/Users/garbade/AppData/LocalLow/MoveBook/MoveBook Farm Adventures\pose_detection.bytes because it already exists
UnityEngine.Logger:Log (UnityEngine.LogType,string,object)
```

**Comment by mgarbade** [comment]
Solved. After importing the .unity package locally no "StreamingAsset" folder was created. I had to copy that folder manually from the clean "MediaPipeUnityProject" into my project (were I previously imported the plugin). 

Hints came from this [thread](https://github.com/homuler/MediaPipeUnityPlugin/issues/290#issuecomment-926252481)

**Comment by homuler** [comment]
@mgarbade Sorry, I've not noticed your comments.
It seems that you've already solved your problem, but this is now mentioned [here](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#load-model-files).

> :warning: To use `StreamingAssetResourceManager`, you need to place dependent assets under `Assets/StreamingAssets`. You can usually copy those assets from `Packages/com.github.homuler.mediapipe/Runtime/Resources`.

**Pull request merged**
