### PR TITLE
fix : Carriage Return On Windows

### PR DESCRIPTION
**Pull request by JIN5EOK**
Problem caused by Carriage Return character not being recognized in Windows

### CODE REVIEW

**Comment by homuler** [comment]
Could you please write down specifically what kind of problems exist?
Especially, in that case, what is the value of `handedness.Label`?

**Comment by JIN5EOK** [comment]
handedness.Label is a label that represents information about the recognized hand.
However, in some Windows environments, labels are sometimes written in a format that includes '\r', such as "Left\\r" or "Right\\r". 
  * In this case, it is not judged as either left or right hand. 
  * A bug caused by this phenomenon can be found in the function that displays different colors on the hand joints depending on the left or right hand.

**Comment by homuler** [comment]
> in some Windows environments

Could you write the reproduction steps in a bit more detail?
In my opinion, the problem is that the line endings in `handedness.txt` are CR+LF instead of LF, and I think we should fix that.

**Comment by JIN5EOK** [comment]
There are no samples in the latest version where this occurs. However, when I run the 'HandTracking' sample scene from version 0.12.0, the colors of the two hand joints appear different on Mac but the same on Windows.

And I couldn't find a place to insert content in handedness.txt, so I had no choice but to insert code to remove '\r'. However, if possible, it would be a good idea to edit the contents of the txt file! 👍

**Comment by homuler** [comment]
Could you confirm that the line endings in `Packages/com.github.homuler.mediapipe/PackageResources/MediaPipe/handedness.txt` and `StreamingAssets/**/handedness.txt` (I forgot the path) are not CR+LF?

**Comment by homuler** [comment]
Then, please fix it.
I'm not sure in what format you installed the plugin, but for example, did you change the line endings when unzipping the `MediaPipeUnityPlugins-all.zip`? (some software may change them automatically)

**Comment by JIN5EOK** [comment]
I'm not sure because I wasn't involved in installing this plug-in on the project at all. But I think this issue was probably caused for a similar reason to what you said. Thank you for your help.

**Pull request closed without merging**
